// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangazon.Migrations
{
    [DbContext(typeof(BangazonDbContext))]
    partial class BangazonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangazon.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Apple Rd.",
                            City = "Nashville",
                            FirstName = "Tion",
                            LastName = "Blackmon",
                            State = "TN",
                            UserId = 1,
                            ZipCode = 37000
                        },
                        new
                        {
                            Id = 2,
                            Address = "HQ",
                            City = "Nashville",
                            FirstName = "Admin",
                            LastName = "(SWE)",
                            State = "TN",
                            UserId = 2,
                            ZipCode = 37000
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<int?>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            IsCompleted = true,
                            OrderDate = new DateTime(2025, 3, 13, 21, 57, 11, 520, DateTimeKind.Local).AddTicks(520),
                            OrderTotal = 25000m,
                            PaymentMethodId = 1
                        });
                });

            modelBuilder.Entity("Bangazon.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("Bangazon.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SecurityCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNumber = "4444-4444-4444-4444",
                            CustomerId = 1,
                            ExpirationDate = new DateTime(2028, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityCode = 778
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int?>("SellerId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Graphics Cards",
                            DateAdded = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The EVGA GeForce RTX 3060 12GB provides players with the ability to vanquish 1080p and 1440p gaming...",
                            ImageUrl = "https://i.pinimg.com/originals/8c/4a/a4/8c4aa4434669caabab3ef0e0fea4958d.jpg",
                            Name = "EVGA GeForce RTX 3060 XC 12GB",
                            Price = 25000m,
                            QuantityAvailable = 25,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Processors",
                            DateAdded = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The AMD Ryzen 7 5800X is built on the Zen 3 architecture, offering 8 cores and 16 threads...",
                            ImageUrl = "https://www.techinn.com/f/13795/137954422/amd-ryzen-7-5800x-3.8ghz.jpg",
                            Name = "AMD Ryzen 7 5800X",
                            Price = 35000m,
                            QuantityAvailable = 15,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Motherboards",
                            DateAdded = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ASUS ROG Strix B550-F Gaming motherboard is designed for AMD Ryzen processors...",
                            ImageUrl = "https://images.anandtech.com/doci/15868/ROG-STRIX-B550-F-GAMING-WI-FI-What_s-inside-the-Box.jpg",
                            Name = "ASUS ROG Strix B550-F Gaming",
                            Price = 18000m,
                            QuantityAvailable = 10,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Memory",
                            DateAdded = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corsair Vengeance RGB Pro series DDR4 memory is designed for high-performance overclocking...",
                            ImageUrl = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449223_sd.jpg",
                            Name = "Corsair Vengeance RGB Pro 32GB",
                            Price = 15000m,
                            QuantityAvailable = 20,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official size and weight, indoor/outdoor use.",
                            ImageUrl = "spalding_nba_ball.jpg",
                            Name = "Spalding NBA Basketball",
                            Price = 2999m,
                            QuantityAvailable = 15,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight and breathable, with Dri-FIT technology.",
                            ImageUrl = "nike_elite_shorts.jpg",
                            Name = "Nike Elite Basketball Shorts",
                            Price = 4500m,
                            QuantityAvailable = 30,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 7,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality composite leather, soft feel and grip.",
                            ImageUrl = "wilson_evolution.jpg",
                            Name = "Wilson Evolution Basketball",
                            Price = 6499m,
                            QuantityAvailable = 20,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iconic design with superior traction and support.",
                            ImageUrl = "jordan_jumpman_shoes.jpg",
                            Name = "Jordan Jumpman Basketball Shoes",
                            Price = 12000m,
                            QuantityAvailable = 10,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compression sleeve for improved circulation and performance.",
                            ImageUrl = "adidas_shooting_sleeve.jpg",
                            Name = "Adidas Shooting Sleeve",
                            Price = 1899m,
                            QuantityAvailable = 25,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Moisture-wicking and cushioned for comfort.",
                            ImageUrl = "ua_basketball_socks.jpg",
                            Name = "Under Armour Basketball Socks",
                            Price = 1499m,
                            QuantityAvailable = 40,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 11,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adjustable height, weather-resistant material.",
                            ImageUrl = "basketball_hoop.jpg",
                            Name = "Basketball Hoop with Stand",
                            Price = 19999m,
                            QuantityAvailable = 5,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 12,
                            Category = "Basketball Products",
                            DateAdded = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Used in official FIBA games, premium feel.",
                            ImageUrl = "molten_game_ball.jpg",
                            Name = "Molten Official Game Ball",
                            Price = 8999m,
                            QuantityAvailable = 12,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 13,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pair of adjustable dumbbells with weight range from 5 to 52.5 lbs.",
                            ImageUrl = "bowflex_selecttech.jpg",
                            Name = "Bowflex SelectTech 552 Adjustable Dumbbells",
                            Price = 34999m,
                            QuantityAvailable = 10,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 14,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-end stationary bike with live and on-demand classes.",
                            ImageUrl = "peloton_bike.jpg",
                            Name = "Peloton Bike+",
                            Price = 249500m,
                            QuantityAvailable = 5,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 15,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable, full-body workout system using suspension straps.",
                            ImageUrl = "trx_trainer.jpg",
                            Name = "TRX Suspension Trainer",
                            Price = 19999m,
                            QuantityAvailable = 15,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 16,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-end treadmill with incline and interactive training.",
                            ImageUrl = "nordictrack_treadmill.jpg",
                            Name = "NordicTrack Commercial 1750 Treadmill",
                            Price = 229999m,
                            QuantityAvailable = 8,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 17,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deep tissue muscle treatment with customizable speed settings.",
                            ImageUrl = "theragun_elite.jpg",
                            Name = "Theragun Elite Percussion Massager",
                            Price = 39999m,
                            QuantityAvailable = 12,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 18,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced fitness tracker with heart rate monitoring and GPS.",
                            ImageUrl = "fitbit_charge6.jpg",
                            Name = "Fitbit Charge 6",
                            Price = 14999m,
                            QuantityAvailable = 20,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 19,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heavy-duty air bike with reinforced steel construction.",
                            ImageUrl = "rogue_echo_bike.jpg",
                            Name = "Rogue Echo Bike",
                            Price = 79500m,
                            QuantityAvailable = 7,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 20,
                            Category = "Fitness Equipment",
                            DateAdded = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight percussion massage gun for muscle recovery.",
                            ImageUrl = "hypervolt_go2.jpg",
                            Name = "Hyperice Hypervolt Go 2",
                            Price = 12999m,
                            QuantityAvailable = 18,
                            StoreId = 3
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StoreId = 1,
                            UserId = 2,
                            Username = "TionB"
                        },
                        new
                        {
                            Id = 2,
                            StoreId = 1,
                            UserId = 1,
                            Username = "Rob90"
                        },
                        new
                        {
                            Id = 3,
                            StoreId = 1,
                            UserId = 3,
                            Username = "BeachVibes98"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC Parts",
                            SellerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sports Products",
                            SellerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fitness Equipment",
                            SellerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Update me",
                            SellerId = 3
                        });
                });

            modelBuilder.Entity("Bangazon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSeller = false,
                            Uid = "zmwuMjpI5RXABj6mImfK2O586Qf1"
                        },
                        new
                        {
                            Id = 2,
                            IsSeller = false,
                            Uid = "eBBiuMs6zCYuRFk5657mXQBemjh1"
                        },
                        new
                        {
                            Id = 3,
                            IsSeller = true,
                            Uid = "change-me-2"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Customer", b =>
                {
                    b.HasOne("Bangazon.Models.Seller", null)
                        .WithMany("Customers")
                        .HasForeignKey("SellerId");

                    b.HasOne("Bangazon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangazon.Models.Order", b =>
                {
                    b.HasOne("Bangazon.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.Seller", null)
                        .WithMany("Orders")
                        .HasForeignKey("SellerId");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Bangazon.Models.OrderItems", b =>
                {
                    b.HasOne("Bangazon.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bangazon.Models.PaymentMethod", b =>
                {
                    b.HasOne("Bangazon.Models.Customer", "Customer")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Bangazon.Models.Product", b =>
                {
                    b.HasOne("Bangazon.Models.Seller", null)
                        .WithMany("Products")
                        .HasForeignKey("SellerId");

                    b.HasOne("Bangazon.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Bangazon.Models.Seller", b =>
                {
                    b.HasOne("Bangazon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangazon.Models.Store", b =>
                {
                    b.HasOne("Bangazon.Models.Seller", "Seller")
                        .WithMany("Stores")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Bangazon.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("Bangazon.Models.Seller", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
